# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SOcMVxQC0EYeDp3M5WactNe3r3FhK8Y0
"""

def sumSubsets(sets, n, target) :
 
    x = [0]*len(sets);
    j = len(sets) - 1;
 
    while (n > 0) :
     
        x[j] = n % 2;
        n = n // 2;
        j -= 1;
     
    sum = 0;
 
    for i in range(len(sets)) :
        if (x[i] == 1) :
            sum += sets[i];
    if (sum == target) :
    print("{",end="");
		for i in range(len(sets)) :
			if (x[i] == 1) :
				print(sets[i],end= ", ");
		print("}, ",end="");


def findSubsets(arr, K) :
  
    x = pow(2, len(arr));
 
    for i in range(1, x) :
        sumSubsets(arr, i, K);

if __name__ == "__main__" :
   
    x = int(input("Enter Array Length"))
    for i in range (0, x):
      y = int(input("Enter Array "))
      arr.append(y)
    K = int(input("Enter sum"))
    findSubsets(arr, K);