# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SOcMVxQC0EYeDp3M5WactNe3r3FhK8Y0
"""

num = int(input("Enter number"))

if num > 1:

    for i in range(2, int(num/2)+1):

        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
 
else:
    print(num, "is not a prime number")